version: '3.8'

services:
  traderpluseditor:
    container_name: traderpluseditor
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - sites_volume:/sites
    command: sh -c "mkdir -p /sites/traderpluseditor && cp -r /src/traderpluseditor/browser/* /sites/traderpluseditor/"
    networks:
      - caddy-network
    restart: "no"

networks:
  caddy-network:
    external: true

volumes:
  sites_volume:
    name: caddy_sites
    external: true