name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    continue-on-error: true  # Allow the workflow to continue even if linting fails
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run linting
        run: npm run lint

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build application
        run: npm run build --configuration=production
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 1
          
  deploy:
  name: Deploy to VPS
  runs-on: ubuntu-latest
  needs: build
  if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
  
  steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        
    - name: Deploy to VPS
      run: |
        # Connect to VPS and perform deployment
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          # Create directory if it doesn't exist
          mkdir -p /home/rdpuser/apps/traderpluseditor
          
          # Clone or pull latest changes
          if [ -d /home/rdpuser/apps/traderpluseditor/.git ]; then
            cd /home/rdpuser/apps/traderpluseditor
            git pull
          else
            # If directory exists but isn't a git repo, remove it
            rm -rf /home/rdpuser/apps/traderpluseditor
            git clone git@github.com:TheDmitri/traderpluseditor.git /home/rdpuser/apps/traderpluseditor
          fi
          
          # Navigate to the project directory
          cd /home/rdpuser/apps/traderpluseditor
          
          # Build and deploy using docker-compose
          docker-compose up --build -d
        "